### ISSUE TITLE
Indicator does not remove spans on items array refresh

### ISSUE THREAD

**Issue by agido-freudenreich** [revolunet/angular-carousel#179]
Hello,

first of all thanks for developing this carousel, nice work!

I´ve discovered a problem with the indicator if you update the items array. Due to the fact that the transition is never ending the old spans (based on the old items array) are not removed. So if you want to change the content dynamically the spans are duplicated on each update.

It can be fixed by adding these styles:

``` css
.rn-carousel-indicator span.ng-leave {
            -webkit-transition: none !important;
            -moz-transition: none !important;
            transition: none !important; 
}
```

Greets
