### ISSUE TITLE
Customize the carousel contorl

### ISSUE THREAD

**Issue by suriyagp** [revolunet/angular-carousel#266]
Can i place the carousel control anywhere on the same page? is this possible??

**Comment by michelem09** [comment]
mmm and how can we change the next/prev character? Put I'd like to use a Font Awesome icon how can I do that?

**Comment by audleman** [comment]
@michelem09 you can change the character in CSS using the :before attribute. Example

```css
.rn-carousel-controls {
    .rn-carousel-control-next:before {
        content: "Continue";
    }
}
```

I replaced the arrow with the word 'Continue'. Not sure how you put a font awesome character in there, but I'm sure you can piece it together.
