### ISSUE TITLE
Dynamic height problem

### ISSUE THREAD

**Issue by AviFix** [revolunet/angular-carousel#309]
Hi,

i ran in to a problem, with dynamic height.

i give the ul the following css:

ul {
    width: 100%;
    min-height:150px;
    max-height:550px;
    background-color:green;
}

but the height is stock on 150px.

example:
http://plnkr.co/edit/kefCFYLR8t7qfa4VUc2C?p=preview

Thanks alot

Avi

**Comment by Rakonda** [comment]
I got the same problem with the height

**Comment by omnibs** [comment]
Same problem here. Seems like it used to work in some older version before `li` tags were position: absolute.

**Comment by wesleyfsmith** [comment]
Yeah, same problem. Any one have an idea?

**Comment by inca** [comment]
Try adding a class on active slide (something like `ng-class='{ active: $index == myIndexVariable }'`); then add CSS `ul[rn-carousel] > li.active { position: relative }`.

**Comment by mariusc23** [comment]
Hi. I was able to get dynamic height working with the following additional styles:

```scss
ul[rn-carousel] {
  > li {
    position: relative;
    margin-left: -100%;
    
    &:first-child {
      margin-left: 0;
    }
  }
}
```
