### ISSUE TITLE
How do I enable show part of next slide?

### ISSUE THREAD

**Issue by SherifSharkawy** [revolunet/angular-carousel#375]
I tried this, but it doesn't work

<ul rn-carousel rn-show-next="5">
  <li>slide #1</li>
  <li>slide #2</li>
  <li>slide #3</li>
</ul>

**Comment by swypse** [comment]
Hi!

Try add some css to li elements:
```css
ul[rn-carousel] > li {
  /* … */
  left: 1em !important; /* set size of visible part of next slide here */
  right: 1em !important; /* and here */
  width: auto !important; /* if width is set to 100% */
}
```
